### PR TITLE
Fix 'Item already exists in list' error.

### PR DESCRIPTION
**Pull request by rhausam**

### CODE REVIEW

**Review by grahamegrieve — COMMENTED** [review]
why does it already exist in FOthers? What's the test case? It shouldn't already exist...

**Comment by rhausam** [comment]
I believe this is where it occurs and can serve as a test case (or a template for one):
`{
  "resourceType": "ValueSet",
  "status": "active",
  "name": "AllergyIntoleranceSubstanceProductSnomedGpsUvIps",
  "id": "allergy-intolerance-substance-product-snomed-gps-uv-ips",
  "title": "Allergy-intolerance substance-product - SNOMED CT GPS - IPS",
  "description": "IPS Allergy-intolerance substance-product GPS value set. This value set includes the codes from the SNOMED International Global Patient Set (GPS) subset of SNOMED CT that are included in: all descendants of 105590001 | Substance (substance); all descendants of 373873005 | Pharmaceutical / biologic product (product).",
  "version": "1.0.0",
  "url": "http://hl7.org/fhir/uv/ips/ValueSet/allergy-intolerance-substance-product-snomed-gps-uv-ips",
  "meta": {
    "profile": [
      "http://hl7.org/fhir/StructureDefinition/shareablevalueset"
    ]
  },
  "experimental": false,
  "date": "2021-05-14T21:56:28-05:00",
  "publisher": "Health Level Seven International - Patient Care Work Group",
  "contact": [
    {
      "telecom": [
        {
          "system": "url",
          "value": "http://www.hl7.org/Special/committees/patientcare"
        }
      ]
    }
  ],
  "jurisdiction": [
    {
      "coding": [
        {
          "code": "001",
          "system": "http://unstats.un.org/unsd/methods/m49/m49.htm"
        }
      ]
    }
  ],
  "immutable": false,
  "copyright": "The GPS is produced by SNOMED International under the terms of the [Creative Commons Attribution 4.0 International Public License](https://creativecommons.org/licenses/by/4.0/)\n\nAdditional information about this license specific to SNOMED International’s release of the GPS:\n* SNOMED CT is © and ® SNOMED International. The right to maintain the GPS remains vested exclusively in SNOMED International.\n* The Licensee can redistribute the GPS.\n* The Licensee can create derivatives or implementation-related products and services based on the GPS.\n* The Licensee cannot claim that SNOMED International or any of its Members endorses the Licensee’s derivative because it uses content from the GPS.\n* Neither SNOMED International nor any of the contributors accept any liability for the Licensee’s use or redistribution of the GPS.\n* SNOMED CT® was originally created by the College of American Pathologists.\n\nWithout obtaining prior written permission from SNOMED International, you are expressly prohibited from using, distributing or reproducing the SNOMED International, SNOMED CT or SNOMED GPS logo, service mark or trademark. Please review all terms and conditions of use [here](http://www.snomed.org/terms-and-conditions).",
  "compose": {
    "include": [
      {
        "system": "http://snomed.info/sct",
        "valueSet": [
          "http://terminology.hl7.org/ValueSet/snomed-intl-gps"
        ],
        "filter": [
          {
            "property": "concept",
            "op": "descendent-of",
            "value": "105590001"
          }
        ]
      },
      {
        "system": "http://snomed.info/sct",
        "valueSet": [
          "http://terminology.hl7.org/ValueSet/snomed-intl-gps"
        ],
        "filter": [
          {
            "property": "concept",
            "op": "descendent-of",
            "value": "373873005"
          }
        ]
      }
    ]
  }
}
`

**Comment by grahamegrieve** [comment]
Solved as part of rewrite for more efficiency importing valuesets

**Comment by rhausam** [comment]
Yes, happy with your solution - the latest commit fixes it.

**Pull request closed without merging**
